Fix some errors, fix some performance warnings, and some simple (but effective) optimizations
trzy/Supermodel pull request #1
Opened 2022-07-11 16:51 UTC by toxieainc

2022-07-17 03:56 UTC, trzy requested changes
Please see the individually addressed items and fix. Thank you!

2022-07-17 03:56 UTC, trzy commented on Src/Graphics/Render2D.cpp
> +      if (!clip || (/*pixelOffset >= 0 &&*/ (unsigned int)pixelOffset < 496u))
The test for pixelOffset >= 0 is required or you will end up writing below index 0 of the surface buffer. Although the buffers are 512 lines wide, rendering begins at offset 0.

2022-07-17 03:56 UTC, trzy commented on Src/Graphics/Render2D.cpp
> +        if (!clip || (/*pixelOffset >= 0 &&*/ (unsigned int)pixelOffset < 496u))
Likewise here. The pixelOffset check is required. I would prefer the check remain for readability as 2D rendering is not a significant performance sink for now. Another option would be to shift the pixel buffers by 8. But I would need to check more carefully to ensure the buffers are laid out as I recall. It appears they are 512*384 at first glance. This solution would need to be clearly documented, however.

2022-07-17 03:56 UTC, trzy commented on Src/Util/ByteSwap.cpp
> +#elif 1 // assume GCC
Is there a way to detect GCC? I think there is a GNUC or some such macro defined. This would be preferred than leaving a pointless #else that is never used.

2022-07-17 03:56 UTC, trzy commented on Src/CPU/68K/Musashi/m68kdasm.c
> +	 "sf", "seq",  "gt",  "ge",  "lt",  "le",  "gl", "gle", /* 010 */
Oooh missing comma, good catch! Does this affect MAME too?

2022-07-17 03:56 UTC, trzy commented on Src/GameLoader.cpp
> +  game->version = game_node["identity/version"].ValueAsDefault<std::string>(std::string());
Any reason for this in particular? I find the former a bit easier on the eyes.

2022-07-17 03:56 UTC, trzy commented on Src/Network/TCPSend.cpp
> +	int sent;
Not a fan of unintialized vars. Why not:

```
int sent = SDLNet_TCP_Send(m_socket, &length, sizeof(int));
```

2022-07-17 03:56 UTC, trzy commented on Src/GameLoader.cpp
> +  if (GameLoader::MissingAttrib(loader, region_node, "name") || MissingAttrib(loader, region_node, "stride") | GameLoader::MissingAttrib(loader, region_node, "chunk_size"))
The | rather than || is intentional. We do *not* want to short-circuit because these functions print useful error messages. With short-circuiting, we would not get a comprehensive error readout. Because this at first glance seems non-obvious, please add a comment to at least one of these (but maybe all of these). E.g.:

```
Non-short-circuiting | is intentional so that all error messages are printed.
```

2022-07-17 03:56 UTC, trzy commented on Src/GameLoader.cpp
> +  if (GameLoader::MissingAttrib(loader, file_node, "name") || GameLoader::MissingAttrib(loader, file_node, "offset"))
| is correct, || is wrong.

2022-07-17 03:56 UTC, trzy commented on Src/Inputs/Inputs.cpp
> +	const size_t hs = strlen(header);
Non-performance critical, prefer readable form over extra line of code.

2022-07-17 18:14 UTC, toxieainc commented on Src/Graphics/Render2D.cpp
> +      if (!clip || (/*pixelOffset >= 0 &&*/ (unsigned int)pixelOffset < 496u))
This one is just an equivalent optimization. As its cast to unsigned, it includes the >=0 check implicitly, thus i left it there, but commented out.

2022-07-17 18:15 UTC, toxieainc commented on Src/Graphics/Render2D.cpp
> +        if (!clip || (/*pixelOffset >= 0 &&*/ (unsigned int)pixelOffset < 496u))
In my profiling this inner loop actually was very noticable. Not the most important, but always under the Top 5.

2022-07-17 18:16 UTC, toxieainc commented on Src/Util/ByteSwap.cpp
> +#elif 1 // assume GCC
I just copied this from other parts of the code base, but will fix it nevertheless.

2022-07-17 18:16 UTC, toxieainc commented on Src/CPU/68K/Musashi/m68kdasm.c
> +	 "sf", "seq",  "gt",  "ge",  "lt",  "le",  "gl", "gle", /* 010 */
No, MAME already had this fixed a long time ago. My next PR will have some more things that are missing/fishy in the old m68k core.

2022-07-17 18:17 UTC, toxieainc commented on Src/Inputs/Inputs.cpp
> +	const size_t hs = strlen(header);
No problem. I just addressed the IMHO sane performance warnings. Will revert.

2022-07-17 18:24 UTC, toxieainc commented on Src/GameLoader.cpp
> +  game->version = game_node["identity/version"].ValueAsDefault<std::string>(std::string());
Not really, just a performance warning.

2022-07-17 18:29 UTC, toxieainc commented
I think i addressed all now, please check again.

2022-07-18 19:43 UTC, toxieainc commented on Src/Graphics/Render2D.cpp
> +      if (!clip || (/*pixelOffset >= 0 &&*/ (unsigned int)pixelOffset < 496u))
Done

2022-07-18 20:00 UTC, trzy commented
Looks great now!

2022-07-18 20:00 UTC, closed without merging