fixed `-Wformat-overflow` compiler warnings / added missing newline to log messages
trzy/Supermodel pull request #115
Opened 2023-12-02 18:18 UTC by firewave

Some examples for reference:
```
Src/OSD/SDL/Main.cpp:1086:30: warning: ‘ (Paused)’ directive writing 9 bytes into a region of size between 1 and 128 [-Wformat-overflow=]
 1086 |         sprintf(titleStr, "%s (Paused)", baseTitleStr);
      |                              ^~~~~~~~~
Src/OSD/SDL/Main.cpp:1086:16: note: ‘sprintf’ output between 10 and 137 bytes into a destination of size 128
 1086 |         sprintf(titleStr, "%s (Paused)", baseTitleStr);
      |         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

```
Src/OSD/Logger.cpp:382:29: warning: ‘%s’ directive writing up to 4095 bytes into a region of size 4088 [-Wformat-overflow=]
  382 |   sprintf(string2, "[Error] %s\n", string1);
      |                             ^~     ~~~~~~~
Src/OSD/Logger.cpp:382:10: note: ‘sprintf’ output between 10 and 4105 bytes into a destination of size 4096
  382 |   sprintf(string2, "[Error] %s\n", string1);
      |   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2023-12-02 22:35 UTC, trzy requested changes
Please see the attached comments. I don't think the buffer lengths should be touched in Logger.cpp, there is no need for it. Rather, use the safe forms of vsprintf and sprintf (vsnprintf and snprintf). Also, the \n in debug logging was intentionally omitted. It's not a typo.

2023-12-02 22:35 UTC, trzy commented on Src/OSD/Logger.cpp
> +  char string2[4105]; // add 8 for the prefix and 1 for newline
These are not needed. 4096 was chosen somewhat arbitrarily. We don't actually check the size of the resulting output. If you want to fix this, you should instead prefer to use vsnprintf() and pass 4096 as the "n" parameter. Likewise, sprintf -> snprintf.

2023-12-02 22:35 UTC, trzy commented on Src/OSD/Logger.cpp
> +  sprintf(string2, "[Debug] %s\n", string1);
This newline is actually incorrect. DebugLog is special and you'll notice wherever it is used in Supermodel, a \n is manually included. The intent behind this was to allow formatting debug output more freely with multiple calls to generate a single line if needed. However, now that the [Debug] tag has been added, it may be worthwhile to automatically include a \n but if this is done, all places where DebugLog is used must be updated to drop their \n.

2023-12-02 22:35 UTC, trzy commented on Src/OSD/Logger.cpp
> +  sprintf(string2, "[Debug] %s\n", string1);
Same here.

2023-12-02 22:35 UTC, trzy commented on Src/OSD/SDL/Main.cpp
> +  char titleStr[256];
This change is fine, I suppose. Does anything actually exceed 128 bytes? We should probably also move to using snprintf() for safety here.

2024-03-10 03:43 UTC, trzy commented
Will you be able to make the suggested changes?

2024-03-11 13:41 UTC, firewave commented
> Will you be able to make the suggested changes?

Yes. Hopefully I finally get to it this week.

2024-03-30 20:12 UTC, firewave commented on Src/OSD/Logger.cpp
> +  sprintf(string2, "[Debug] %s\n", string1);
Done.

2024-03-30 20:13 UTC, firewave commented on Src/OSD/Logger.cpp
> +  sprintf(string2, "[Debug] %s\n", string1);
Done.

2024-03-30 20:19 UTC, firewave commented on Src/OSD/SDL/Main.cpp
> +  char titleStr[256];
As it appends up to 128 bytes from `baseTitleStr` in that string it needs to be at least `128 + n`.

```
Src/OSD/SDL/Main.cpp:1086:30: warning: ‘ (Paused)’ directive writing 9 bytes into a region of size between 1 and 128 [-Wformat-overflow=]
 1086 |         sprintf(titleStr, "%s (Paused)", baseTitleStr);
      |                              ^~~~~~~~~
Src/OSD/SDL/Main.cpp:1086:16: note: ‘sprintf’ output between 10 and 137 bytes into a destination of size 128
 1086 |         sprintf(titleStr, "%s (Paused)", baseTitleStr);
      |         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2024-03-30 20:29 UTC, firewave commented on Src/OSD/Logger.cpp
> +  char string2[4105]; // add 8 for the prefix and 1 for newline
Okay. I moved back to the original buffer length and use `*snprintf()` now.

2024-03-30 20:34 UTC, firewave commented
There are additional warnings now but I cannot change that file because there are some issues with the line endings.

```
Src/Debugger/CPU/68KDebug.cpp:1353:56: note: ‘sprintf’ output between 15 and 64 bytes into a destination of size 50
 1353 |                                                 sprintf(moveStr, "movem.%c %s,[AM2]", sizeC, regList);
      |                                                 ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2026-07-26 19:50 UTC, trzy commented
Closed because no longer needed (the warnings have been fixed).

2026-07-26 19:50 UTC, closed without merging