Small optimizations and fix pointer aliasing
trzy/Supermodel pull request #17
Opened 2022-08-19 19:40 UTC by toxieainc

Harmless math warning fixes/optimizations, no functional change (apart from being faster as no double<->float casts).
Change map->unordered_map in CNew3D::CacheModel (as no order needed there).
Avoid general pointer aliasing problems (using bit_cast (C++20 if available), or the recommended/compiler-optimized-away memcpy) to be more future proof.

2022-08-19 22:31 UTC, dukeeeey commented
Unordered map isn't automatically faster. The implementation is usually some form of hash table so will likely allocate a good chunk of memory. For smaller tables just a regular map can be a lot more efficient. 

I don't see the point of bit cast. I'm sure it'll compile to identical code. It just obfuscate exactly what the code is doing for me.

2022-08-20 07:10 UTC, toxieainc commented
I would have totally agreed on both 10 or 15 years ago.

The mem overhead of unordered maps should be neglibile here, simply as its overall just a tiny fraction of the overall mem usage of Supermodel. Performance wise it is in the vast majority of cases superior with all 'common' compiler versions from the last years.

As for the bit casts: The problem is that compilers (especially gcc and also more and more clang) get extremely aggressive nowadays, and everything that is essentially undefined behavior can and will be exploited. So unless one specifies special compile options, strict aliasing is always enabled on the higher optimization levels.

See e.g. https://gist.github.com/shafik/848ae25ee209f698763cffee272a58f8
and for GCC: 'The -fstrict-aliasing option is enabled at levels -O2, -O3, -Os.'

For MSVC this is usually not a problem (at the moment!), but i've seen gcc 'break' such code already in our own production code.

2022-08-20 08:34 UTC, dukeeeey commented
For maps it depends on the use case. If you create an unordered map inside a function call and it only lives for the duration of the function call there is a good chance you'll hit the kernel/os to allocate more memory from the heap. This is the expensive part and where the slowness comes from. Small maps are much less likely to have this problem as the memory can come from already allocated memory from a memory pool managed by malloc. Of course this answer is highly implementation dependent but is generally true. So you can't just blindly swap out map for a hash table version and expect it to go faster. But if you can profile the code and it's a hot spot and a hash table version is faster then of course it's a no brainer to swap them out.

As for the casting code. If I am  being pedantic you made the c++ function into a macro function which is generally a horrible idea. If you don't know exactly what you are doing with parenthesis you can get entirely the wrong result. That is one of the weaknesses of using macros.

2022-08-20 12:20 UTC, toxieainc commented
I agree for the general case. But in this case the macro is directly wiring the param through to each function call, which IMHO makes the sideeffects 0, as it looks like a function and actually behaves like the called function, too.

2022-08-22 20:33 UTC, toxieainc commented
I also just did some benchmarking (windows/VS2019) regarding unordered_map vs map. Timing was done using the high resolution timer/perf counter, accumulating over 10000s of CacheModel calls. Overall its no large difference, but unordered_map is a bit faster across multiple tested games.

2022-08-25 15:03 UTC, trzy commented
I haven’t yet looked at this in detail (traveling for another week or so) and don’t have a strong opinion about the map data structure.

Otherwise, as a general principle, I think readability should be prioritized above performance (unless we are going for a *big* perf win), with deference given to the person who will be spending most time maintaining the code (almost always the person who wrote it). 

I do think that it is worthwhile to clean up the various compiler warnings being spewed.

So let’s see if we can come to a compromise here.

2022-08-25 15:08 UTC, trzy commented on Src/Graphics/New3D/R3DFloat.cpp
> +#include "Util\GenericValue.h"
Shouldn’t we use forward slash / for paths?

2022-08-25 19:58 UTC, toxieainc commented on Src/Graphics/New3D/R3DFloat.cpp
> +#include "Util\GenericValue.h"
True, thanks, corrected.

2022-08-25 20:01 UTC, toxieainc commented
As for readability vs perf: Absolutely, but the bit casts are there for conformance with cpp standards. As mentioned otherwise, it may(!) happen that compilers exploit this undefined behavior (i.e. potentially resulting in hard to track down bugs).
I'm also not keen on using these, but as compilers are really aggressive nowadays.. .. ..

2022-08-25 20:40 UTC, dukeeeey commented
Normal casts are part of the core language and will be there forever. Bit_cast can be done at compile time for say constant expressions. But this doesn't really help us in supermodel

2022-08-25 20:57 UTC, toxieainc commented
These will be there forever, yes. And i also used these with great joy ;) for years and years.

BUT compilers nowadays can (and will) exploit the spec, see the link above (https://gist.github.com/shafik/848ae25ee209f698763cffee272a58f8).
So either one has to use some 'official' workarounds (bit_cast or memcpy) or has to disable strict aliasing (e.g. -fno-strict-aliasing for gcc, like parts of Linux does).

2022-08-25 21:09 UTC, toxieainc commented
From https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#Type-punning:
'In particular, an object of one type is assumed never to reside at the same address as an object of a different type, unless the types are almost the same. For example, an unsigned int can alias an int, but not a void* or a double.'
So for the places i changed, this is exactly the case. So i don't like this fact, too, but nowadays it is like it is.  :/

2022-08-26 01:20 UTC, dukeeeey commented
Okay, makes sense.

2022-08-27 10:09 UTC, ToBul commented
@toxieainc
Sorry for butting in but I tried your branch; to get it to build in gcc I had to remove the 'std::' scope from memcpy.

2022-09-13 20:35 UTC, trzy commented
Hey sorry this has been stuck in PR hell. I'll be back home on Friday and can look at this on Saturday. I think it's probably safe to merge.

2022-09-24 18:15 UTC, trzy reviewed
I think I'm about ready to merge this in. Sorry for the delay. Just had a question about this use of unions rather than a more straightforward reinterpret cast.

2022-09-24 18:15 UTC, trzy commented on Src/Util/GenericValue.h
> +inline float uint_as_float(const unsigned int i)
How does this differ from a reinterpret_cast? Why not use one?

2022-09-24 19:52 UTC, toxieainc commented on Src/Util/GenericValue.h
> +inline float uint_as_float(const unsigned int i)
Its a can of worms and totally stupid/unnecessary c++ mess, really. :(
So far i found that only bit_cast and memcpy are 'accepted' and defined-behavior variants to do such specific casts.
The additional union code i only left in for another possible way (which only GCC explicitly specs as 'fine' though, as one of its language extensions).

If you look at https://en.cppreference.com/w/cpp/language/reinterpret_cast it also avoids to really get into details for everything except pointer/reference stuff, and thus it also seems to be regarded by the community as UB for doing these specific casts.  :/

I also verified that memcpy and bit_cast both end up in optimized away code via godbolt. (e.g. https://godbolt.org/z/M713r79fT  &  https://godbolt.org/z/3K7b3dbvP )

2022-09-26 04:46 UTC, trzy commented on Src/Util/GenericValue.h
> +inline float uint_as_float(const unsigned int i)
I think for the task of converting from a uint8_t array, reinterpret_cast actually does work as intended. And certainly bit_cast should. reinterpret_cast<> is supposed to work for converting objects that are represented as std::byte, char, or unsigned char (and I assume uint8_t basically falls into this category).

Are you sure a union is well defined here? Like couldn't, in theory, this use of a union be UB?

2022-09-26 08:07 UTC, dukeeeey commented on Src/Util/GenericValue.h
> +inline float uint_as_float(const unsigned int i)
My understanding of the spec in c this is allowed but in c++ it's undefined behaviour. But basically every compiler will support this.

In c++ byte pointer to another type isn't undefined behaviour. 

I do agree that it's a good idea to get away from undefined behaviour. But maybe there are better ways we can fix this in the code such as returning void* and just casting to type we want. Rather than returning int* then recasting. I don't think our existing code is problematic though because we are never writing one type and reading back as another with the exception of my real3dpro float code. That could potentially trigger undefined behaviour I believe. It should be fixed.

2022-09-26 15:54 UTC, dukeeeey commented on Src/Util/GenericValue.h
> +inline float uint_as_float(const unsigned int i)
From the spec

It's undefined behavior to read from the member of the union that wasn't most recently written.
https://en.cppreference.com/w/cpp/language/union

Goes on to say
Many compilers implement, as a non-standard language extension, the ability to read inactive members of a union.

2022-09-27 14:27 UTC, toxieainc commented on Src/Util/GenericValue.h
> +inline float uint_as_float(const unsigned int i)
Absolutely agreed, thats also why the union code is not used (there is a `#if 1` so that always the memcpy path is used if `bit_cast`/C++20 is not already available to the compiler yet).

Which places you guys think i should _not_ use these new `(u)int_as_float` or `float_as_(u)int`s then?

2022-09-27 14:31 UTC, toxieainc commented on Src/Util/GenericValue.h
> +inline float uint_as_float(const unsigned int i)
..or actually, as i only changed 3 places: Which `ToFloat` locations should i change in addition (i.e. to not use the new functions)?

2022-09-30 23:31 UTC, trzy commented on Src/Util/GenericValue.h
> +inline float uint_as_float(const unsigned int i)
Looks like these functions are used in Legacy3D.cpp and R3DFloat.cpp. I didn't notice the #elif 1. I see now what's going on -- I had skimmed that and missed it and was confused. I think these functions are fine then. But here's what I recommend:

1. Remove them from GenericValue.h. Doesn't seem like they belong here. Maybe their own header file?
2. They should be in the Util namespace. 
3. Naming convention should match the rest of Supermodel. E.g., camel case. Util::ToFloat() or something like that.

2022-10-01 01:45 UTC, toxieainc commented on Src/Util/GenericValue.h
> +inline float uint_as_float(const unsigned int i)
Okay, i just commited your requests

2022-10-03 00:21 UTC, trzy requested changes

2022-10-03 00:21 UTC, trzy commented on Src/Util/BitCast.h
> +#else
This is never executed if I understand correctly. Let's remove it altogether.

2022-10-03 00:21 UTC, trzy commented on Src/Util/BitCast.h
> +#define FloatAsInt(x) std::bit_cast<int>(x)
Should we be more specific here and replace Int and Uint with Int32 and UInt32 (using either INT32/UINT32 or int32_t/uint32_t)?

2022-10-03 00:22 UTC, trzy commented on Src/Util/BitCast.h
> +#else
That is, the #else clause with the union stuff.

2022-10-03 02:32 UTC, toxieainc commented on Src/Util/BitCast.h
> +#else
Done

2022-10-03 02:32 UTC, toxieainc commented on Src/Util/BitCast.h
> +#define FloatAsInt(x) std::bit_cast<int>(x)
Done

2022-10-04 00:59 UTC, trzy approved these changes
Looks great!

2022-10-04 01:00 UTC, merged