New JTAG implementation
trzy/Supermodel pull request #182
Opened 2024-08-14 12:12 UTC by gm-matthew

Sega Rally 2 and Star Wars Trilogy no longer require patches to run; these patches have been removed from Games.xml (although the games will still function just fine with the patches left intact).

Step 2.x games now display "daughter board was detected" or similar as they do on real hardware.

The savestate file version has been updated so old savestates will not work; we may revert this before committing to provide partial support for old savestates.

We do not yet implement the white flash which is triggered by setting the "block culling" bit in the Mercury modeword; this should be easy to do.

2024-08-14 18:45 UTC, dukeeeey commented
char* str = new char[MAX_REGISTER_LENGTH + 1];
This leaks? There is no free? :)
You could use
std::unique_ptr<char[]> str(new char[MAX_REGISTER_LENGTH + 1]);
or just call
delete [] str;

Also I'd personally avoid the global MAX_REGISTER_LENGTH
I'd make it a public static const variable and stuff it in the CJTAGDevice class.
Less likely to have collisions with global namespace then

But otherwise looks great :)

2024-08-15 11:04 UTC, dukeeeey commented
m_shiftRegSize
This is a size_t variable, which means it'll be different sizes depending on platform, ie if people build a 32build for example. These saves states will break between versions. This is a very bad idea lol

uint32_t is enough. Size_t is 64 bit under win64.

I personally try and avoid these variable length variables unless you really need them (ie to store a pointer or something)

2024-08-15 12:22 UTC, gm-matthew commented
Fair point about size_t, forgot that 32-bit builds are still a thing. Will change it to uint32_t

2024-08-18 06:29 UTC, trzy requested changes
This is awesome! Thank you for putting in the effort to do this. My only real suggested changes are to add a paragraph or two of explanation on your findings at the top of one of the files, wherever you deem appropriate. The logic is very readable but I think it's good to have a bird's eye overview, especially if it's possible to cross-reference any documentation that we have (i.e., the SDK header files, JTAG spec, etc.) if only to jog our memories in the future if something needs to be changed (e.g., I think the VROM test is done via JTAG boundary scan and could someday be emulated here).

2024-08-18 06:29 UTC, trzy commented on Src/Model3/JTAG.cpp
> +    m_earth1(real3D, CASIC::Name::Dummy),
These dummy devices are just shadows of the same device right? Do we know how this works? I assumed that the JTAG shift registers are physically located inside each ASIC. How can there be copies like this? Is it possible instead that the shift registers inside these ASICs are actually 2x or 4x (in the case of Mars) as big, and internally the same data is replicated N times? 

That is, could this also be handled by having only a single ASIC but then increasing the internal shift register size and replicating the ID code, mode word, etc.? This would complicate the interface (e.g., you'd need an extra parameter in the constructors to indicate how many times to replicate -- 2 or 4.

Perhaps a comment at the top of the file describing what's going on?

2024-08-18 06:29 UTC, trzy commented on Src/Model3/JTAG.cpp
> +        m_real3D.WriteJTAGModeword(m_deviceName, m_modeword);
What is the "mode word"? I assume this is a Real3D specific thing that they put in all their ASICs? Would it be possible to elaborate on what this is and how it was discovered (especially if there is any documentation to cross-reference; I can't remember if it appears in the SDK or not) in a descriptive comment at the top of one of the files?

2024-08-18 06:29 UTC, trzy commented on Src/Model3/JTAG.h
> +        &m_jupiter,
Although it is pretty obvious from reading the code that these should not be reordered it might make sense to add a one-line comment to the effect of "Do not reorder. This is the order in which devices appear in the bit stream."

2024-08-18 06:29 UTC, trzy commented on Src/OSD/SDL/Main.cpp
> +static const int STATE_FILE_VERSION = 4;  // save state file version
This is good -- I think trying to back out fragments of the JTAG state (like maybe the modewords) from existing save states would be a huge mess. I'm good with the save state version being bumped forward.

2024-08-18 06:34 UTC, trzy commented
Oh -- and one last thing: my old BitRegister data structure won't be necessary anymore. You can go ahead and remove it from the project.

2024-08-18 12:22 UTC, gm-matthew commented on Src/Model3/JTAG.cpp
> +        m_real3D.WriteJTAGModeword(m_deviceName, m_modeword);
The mode word appears prominently in the Real3D firmware which is how I discovered it; it certainly does appear to be a Real3D specific thing that all the ASICs use.

I made a post on the old forum that lists all of the modeword bits for each ASIC as described in the firmware: https://supermodel3.com/ArchivedForum/192.168.0.100/Forum/viewtopic47b9.html?f=7&t=2282&sid=cef2229983e7ae61b43df8e35d27077f

The sun-clamp disable bit in the Mars ASIC is listed as unused, but I'm guessing that it was added in a later revision because it is definitely used by both Daytona 2 PE and L.A. Machineguns.

2024-08-18 12:44 UTC, gm-matthew commented on Src/Model3/JTAG.cpp
> +    m_earth1(real3D, CASIC::Name::Dummy),
If we take the Mars ASIC for example, there are two of them on step 1,x and four of them on step 2.x. Each of them has their own shift register, modeword, etc. In theory you could disable sun clamping for only one Mars ASIC and it would only affect every other pixel on step 1.x and additionally only on odd/even scanlines on step 2.x.

This would be difficult to emulate accurately since we just use OpenGL to render the whole thing, so I made it so that only the first of each ASIC is hooked up to the CReal3D class; the dummy device just tells it to do nothing.

2024-08-18 12:51 UTC, dukeeeey commented
Dumb question maybe about jtag. Aren't they all connected together? I thought the output of 1 connected to the input of another. So a sort of giant shift register.

2024-08-18 13:27 UTC, gm-matthew commented
> Dumb question maybe about jtag. Aren't they all connected together? I thought the output of 1 connected to the input of another. So a sort of giant shift register.

They are all connected together so they do effectively act like one giant shift register, which is how the old implementation treated it. However, this "giant shift register" can change size depending on the instruction - the old implementation was fixed at 197 bits, which worked for the IDCODE instruction applied to all ASICs but not really for anything else.

2024-08-23 16:27 UTC, trzy approved these changes

2024-08-23 16:28 UTC, merged