Keep Supermodel files (config, nvram, saves, etc.) in predictable paths
trzy/Supermodel pull request #44
Opened 2022-11-14 19:12 UTC by casasfernando

Keep Supermodel files (config, nvram, saves, etc.) in predictable paths when running on Linux.
Be default it will check for Config directory presence in current directory, then it will check in $HOME/.supermodel and finally it will check in $HOME/.config/supermodel.
It will also automatically create any missing directories for NVRAM, saves, screenshots, etc. If $HOME/.config/supermodel is used then all directories except Config will be created in $HOME/.local/share/supermodel.

2022-11-20 21:57 UTC, trzy requested changes
Overall looks good. A few things to address that should be relatively simple. Let me know if you need help with the screenshot filename formatting.

The issue of the log and screenshot directories will need a decision. If we introduce a Screenshots directory, I think the Makefile should create it and add a DIR.txt file describing it, at least on Windows where the directories are not being auto-created. I forget if this happens now with other requires directories like Saves, NVRAM, etc. This could be part of a separate commit.

2022-11-20 21:57 UTC, trzy commented on Src/OSD/FileSystemPath.h
> +    enum fsPathType { Analysis, Config, Log, NVRAM, Saves, Screenshots }; // Filesystem path types
fsPathType -> FSPathType or just PathType (consistent with current enum naming convention).

2022-11-20 21:57 UTC, trzy commented on Src/OSD/SDL/Main.cpp
> +    sprintf(file, "%sScreenshot %.4d-%.2d-%.2d (%.2d-%.2d-%.2d).bmp", FileSystemPath::GetPath(FileSystemPath::Screenshots).c_str(), 1900 + ltm->tm_year, 1 + ltm->tm_mon, ltm->tm_mday, ltm->tm_hour, l
I think this should be converted to a Util::Format() string builder. We currently lack format specifiers for numbers and dates but it should be possible. I think STL now has some sort of date formatters that can be used to assist with building these strings, too?

2022-11-20 21:57 UTC, trzy commented on Src/OSD/Unix/FileSystemPath.cpp
> +            case Screenshots:
I would add a default case. And I think that case should print an error and bring down Supermodel. We don't have a great way of doing this right now but I think you could probably throw a fatal exception to kill the application. The reason for this is to guard against programmer errors. For example, if someone adds an enum case and forgets to update the switch statements. Some languages will guard against this but C++ doesn't do this.

2022-11-20 21:57 UTC, trzy commented on Src/OSD/Unix/FileSystemPath.cpp
> +		if (pwd)
Some sort of indentation issues here.

2022-11-20 21:57 UTC, trzy commented on Src/OSD/Unix/FileSystemPath.cpp
> +            case Analysis:
Prefer case statements to be aligned with the braces of the switch statement. That is, remove one indent level.

2022-11-20 21:57 UTC, trzy commented on Src/OSD/Unix/FileSystemPath.cpp
> +		struct passwd* pwd = getpwuid(getuid());
Indentation.

2022-11-20 21:57 UTC, trzy commented on Src/OSD/Unix/FileSystemPath.cpp
> +
Remove empty line.

2022-11-20 21:57 UTC, trzy commented on Src/OSD/Unix/FileSystemPath.cpp
> +        if (stat(fileSystemPath.c_str(), &pathInfo) == 0 && S_ISDIR(pathInfo.st_mode))
Not a huge deal since this is intended to run on UNIX systems but does the standard library still lack such functions?

2022-11-20 21:57 UTC, trzy commented on Src/OSD/Unix/FileSystemPath.cpp
> +                if (!FileSystemPath::PathExists(strPathType)) mkdir(strPathType.c_str(), 0775);
Formatting: Move mkdir to its own line enclosed with braces as elsewhere.

2022-11-20 21:57 UTC, trzy commented on Src/OSD/Unix/FileSystemPath.cpp
> +                if (!FileSystemPath::PathExists(finalPath)) mkdir(finalPath.c_str(), 0775);
Prefer if-statements to be multi-line with braces.

2022-11-20 21:57 UTC, trzy commented on Src/OSD/Unix/FileSystemPath.cpp
> +                if (!FileSystemPath::PathExists(finalPath)) mkdir(finalPath.c_str(), 0775);
Prefer if-statements to be multi-line with braces.

2022-11-20 21:57 UTC, trzy commented on Src/OSD/Unix/FileSystemPath.cpp
> +                if (!FileSystemPath::PathExists(finalPath)) mkdir(finalPath.c_str(), 0775);
Prefer if-statements to be multi-line with braces.

2022-11-20 21:57 UTC, trzy commented on Src/OSD/Unix/FileSystemPath.cpp
> +                if (!FileSystemPath::PathExists(finalPath)) mkdir(finalPath.c_str(), 0775);
Prefer if-statements to be multi-line with braces.

2022-11-20 21:57 UTC, trzy commented on Src/OSD/Unix/FileSystemPath.cpp
> +        if (finalPath != "") finalPath = Util::Format() << finalPath << "/";
Prefer if-statements to be multi-line with braces.

2022-11-20 21:57 UTC, trzy commented on Src/OSD/Unix/FileSystemPath.cpp
> +                strPathType = "Log";
I'm not sure about this discrepancy in log and screenshot paths on UNIX vs. Windows. Would it be bad to have them follow the Windows convention?

Alternatively, we could add a Screenshot directory to the base of the Supermodel repo. Logs I'm not sure about. Need to think about whether it warrants its own directory. My gut instinct is 'no'.

2022-11-21 20:39 UTC, casasfernando commented on Src/OSD/Unix/FileSystemPath.cpp
> +		if (pwd)
Fixed.

2022-11-21 20:40 UTC, casasfernando commented on Src/OSD/Unix/FileSystemPath.cpp
> +            case Analysis:
Fixed.

2022-11-21 20:41 UTC, casasfernando commented on Src/OSD/Unix/FileSystemPath.cpp
> +		struct passwd* pwd = getpwuid(getuid());
Fixed.

2022-11-21 20:41 UTC, casasfernando commented on Src/OSD/Unix/FileSystemPath.cpp
> +
Fixed.

2022-11-21 20:42 UTC, casasfernando commented on Src/OSD/Unix/FileSystemPath.cpp
> +        if (stat(fileSystemPath.c_str(), &pathInfo) == 0 && S_ISDIR(pathInfo.st_mode))
As far as I could research it seems it does. Do you want me to do something about it or it's ok to leave it as is?

2022-11-21 20:44 UTC, casasfernando commented on Src/OSD/Unix/FileSystemPath.cpp
> +                if (!FileSystemPath::PathExists(strPathType)) mkdir(strPathType.c_str(), 0775);
Fixed.

2022-11-21 20:48 UTC, casasfernando commented on Src/OSD/Unix/FileSystemPath.cpp
> +                if (!FileSystemPath::PathExists(finalPath)) mkdir(finalPath.c_str(), 0775);
Fixed.

2022-11-21 20:48 UTC, casasfernando commented on Src/OSD/Unix/FileSystemPath.cpp
> +                if (!FileSystemPath::PathExists(finalPath)) mkdir(finalPath.c_str(), 0775);
Fixed.

2022-11-21 20:48 UTC, casasfernando commented on Src/OSD/Unix/FileSystemPath.cpp
> +                if (!FileSystemPath::PathExists(finalPath)) mkdir(finalPath.c_str(), 0775);
Fixed.

2022-11-21 20:49 UTC, casasfernando commented on Src/OSD/Unix/FileSystemPath.cpp
> +                if (!FileSystemPath::PathExists(finalPath)) mkdir(finalPath.c_str(), 0775);
Fixed.

2022-11-21 20:49 UTC, casasfernando commented on Src/OSD/Unix/FileSystemPath.cpp
> +        if (finalPath != "") finalPath = Util::Format() << finalPath << "/";
Fixed.

2022-11-21 20:51 UTC, casasfernando commented on Src/OSD/FileSystemPath.h
> +    enum fsPathType { Analysis, Config, Log, NVRAM, Saves, Screenshots }; // Filesystem path types
Fixed.

2022-11-21 21:00 UTC, casasfernando commented on Src/OSD/Unix/FileSystemPath.cpp
> +                strPathType = "Log";
IMHO the whole point of this PR is to be able to find all Supermodel related files (and yes, that includes screenshots and the log) in a predictable common path to avoid having files spread on different places depending on which directory the user was sitting when executing Supermodel. No matter where the user was when he called the binary, he will always find all the files in the same predictable place keeping things nice and tidy.
And this should be the same on every platform if you ask me. :smile: 

Just my two cents.

2022-11-21 21:04 UTC, casasfernando commented on Src/OSD/SDL/Main.cpp
> +    sprintf(file, "%sScreenshot %.4d-%.2d-%.2d (%.2d-%.2d-%.2d).bmp", FileSystemPath::GetPath(FileSystemPath::Screenshots).c_str(), 1900 + ltm->tm_year, 1 + ltm->tm_mon, ltm->tm_mday, ltm->tm_hour, l
In all honesty I have no clue. :smile:
I can do some research and see what I can come up with.
Just bear in mind that I wanted to touch the existing code as less as possible due to me not being skilled in C++. "If it works, don't touch it!" :smile:

2022-11-21 21:19 UTC, casasfernando commented on Src/OSD/Unix/FileSystemPath.cpp
> +            case Screenshots:
What about using a null string as default case? That would translate to current directory in Windows and Linux (if Config is in current path) or ~/.supermodel or ~/.local/share/supermodel depending on which path exists.

What do you think? It's simpler than bringing down Supermodel on error.

2022-11-21 21:32 UTC, casasfernando commented
@trzy just pushed a commit based on some of your comments (already marked them as resolved).
Only three outstanding things to make a decision on, so I can change the code accordingly.

Looking forward your thoughts.

Thanks.

2022-11-25 23:18 UTC, trzy commented
Thanks, I will take a closer look this weekend!

2022-11-29 00:26 UTC, trzy commented
Sorry for the delay I will try to get to it this week later. Been a really busy weekend. I think we are almost there and I might suggest the Util::Format() modifier we need.

2022-12-04 07:22 UTC, trzy reviewed
Looking good. Final stretch here.

2022-12-04 07:22 UTC, trzy commented on Src/OSD/SDL/Main.cpp
> +    sprintf(file, "%sScreenshot %.4d-%.2d-%.2d (%.2d-%.2d-%.2d).bmp", FileSystemPath::GetPath(FileSystemPath::Screenshots).c_str(), 1900 + ltm->tm_year, 1 + ltm->tm_mon, ltm->tm_mday, ltm->tm_hour, l
Okay, let's get this over the finish line. Here is the change that will make this look correct: 

```
void Screenshot()
{
    // Make a screenshot
    time_t now = std::time(nullptr);
    tm* ltm = std::localtime(&now);
    std::string file = Util::Format() << filepath
        << "Screenshot_"
        << std::setfill('0') << std::setw(4) << (1900 + ltm->tm_year)
        << '-'
        << std::setw(2) << (1 + ltm->tm_mon)
        << '-'
        << std::setw(2) << ltm->tm_mday
        << "_("
        << std::setw(2) << ltm->tm_hour
        << '-'
        << std::setw(2) << ltm->tm_min
        << '-'
        << std::setw(2) << ltm->tm_sec
        << ").bmp";

    std::cout << "Screenshot created: " << file << std::endl;
    SaveFrameBuffer(file);
}
```
These std format specifiers are stateful and more than a bit annoying. For example, std::setfill() gets set until it is unset for the entire stream but setw() only affects the following element and is then reset each time. What an awful API! Eventually we could just write a Util::Int() or Util::Uint() that does this automatically but this is fine for now.

2022-12-04 07:22 UTC, trzy commented on Src/OSD/Unix/FileSystemPath.cpp
> +        if (stat(fileSystemPath.c_str(), &pathInfo) == 0 && S_ISDIR(pathInfo.st_mode))
Since this is under the OSD/Unix/ directory, then yes, this is fine for now.

2022-12-04 18:45 UTC, casasfernando commented
@trzy I just pushed another commit to sort out the screenshot function as requested.

Are we good to go or you want to take another look at this?

Thanks!

2022-12-04 21:16 UTC, trzy commented
I think we are good but I'd like to give it a test in Ubuntu. I will try to do that tonight but if I don't get to it by tomorrow night I'll trust it's okay and just merge it in.

2022-12-04 21:52 UTC, casasfernando commented
Perfect. I tested it in Ubuntu 20.04 already (config, nvram, screenshots and savestates) successfully so you may want to try a different version like 22.04.

2022-12-06 05:16 UTC, trzy commented
I didn't have time to test in Linux and I couldn't build successfully on MacOS but there is one last thing: has the MacOS Makefile been modified to continue to compile? I believe it needs one of the FileSystem.cpp implementations. Probably the UNIX one will work but if you can't test it, then use the default one.

2022-12-06 12:33 UTC, casasfernando commented
Sorry for the oversight. Indeed I didn't modify the Makefile for macOS.
Just added a commit to sort that out and also built and tested it successfully on MacBook Pro (M1).
I used the default cpp file, same as Windows, since I'm not sure which would be the correct/expected path for the files in macOS and I prefer to keep it unmodified from the current behavior (same as Windows).

2022-12-13 00:49 UTC, merged