Some CPU updates and small/harmless optimizations
trzy/Supermodel pull request #5
Opened 2022-07-18 20:48 UTC by toxieainc

2022-07-20 18:29 UTC, trzy commented
This one might take me a while to get through. I'm in crunch mode on a different project right now but will try to look throughout the next week. The CPU changes require some close scrutiny. I'm surprised to see changes to some pretty basic instructions in the PowerPC core that I was certain were emulated correctly.

2022-07-20 20:56 UTC, toxieainc commented
PowerPC is basically untouched, i just tried to make the compilers life easier there (simple optimizations with no functional change).
Only Z80 and M68K feature real changes, but most of them rather harmless. Only one M68K change i would think of as severe, as previously it touched out of bounds memory: https://github.com/trzy/Supermodel/pull/5/commits/52067d036c2395f9b94e01dd3049e29dcca07825#diff-45ce0215fdf46faf7104219b13eee8e51686bbe4985074d0deab29f23909085dL239

2022-07-20 21:00 UTC, toxieainc commented
The M68K and Z80 changes are also straight ports from MAME/MESS. I didn't want to pull each and everything over though, only the changes i considered rather harmless AND also making sure that i didn't throw something away that you guys touched independently from MAME in the meantime.

2022-07-20 21:59 UTC, dukeeeey commented
I can't speak for Bart but commits with mostly cosmetic changes are quite annoying.  Also adds to the chance of breaking something unintentionally. We either have to test and go through everything or just merge the changes and hope for the best.

2022-07-21 05:49 UTC, toxieainc commented
It depends on what you understand under cosmetic changes. The M68K and Z80 changes are real fixes ported over from MAME/MESS, not just reformatting or the like. Cause the latter i also think are just distractions.

I could omit the PowerPC changes though if you think these are unnecessary.

2022-07-21 05:52 UTC, toxieainc commented
I would like to keep the changes done to check_condition_code() though, as there i actually double checked with godbolt that better code falls out AND as that one is actually really performance critical (shows up in top spots during profiling via the opcodes/functions that need to use it).
Functionality is 100% the same.

2022-07-21 16:07 UTC, trzy commented
I’ll take a look at it later this week/this weekend. Is this making an actual difference in frame rate? Not many systems struggle with Supermodel these days. I think some of the code in the CPU emulator is structured to reflect the logic descriptions in the PowerPC ISA manual so we don’t want to obscure that logic too much. 

Sent from my iPhone

> On Jul 20, 2022, at 10:52 PM, toxie ***@***.***> wrote:
> 
> ﻿
> I would like to keep the changes done to check_condition_code() though, as there i actually double checked with godbolt that better code falls out AND as that one is actually really performance critical (shows up in top spots during profiling via the opcodes/functions that need to use it).
> Functionality is 100% the same.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.

2022-07-21 21:31 UTC, toxieainc commented
The PPC profiling for Daytona2 shows that the ppc_execute goes down by 3.5% (averaged over 3 runs of both variants (old and new)). So nothing earth shattering, but also not nothing.
As said, basically only check_condition_code() should make a real difference here, and i don't think that readability or anything else is really affected by the change, IMHO rather the opposite (as one can/should rely that all results are always just 0 or 1).

2022-07-21 21:33 UTC, toxieainc commented
(oh, and ppc_execute is >50% of CPU on my machine when disabling throttling and vsync)

2022-07-30 00:48 UTC, trzy commented
I will take a look at this next week when I'm back home. I've been tied up with my startup this week and last.

2022-07-30 12:09 UTC, toxieainc commented
No hurry..

2022-08-07 21:37 UTC, trzy requested changes
I have not verified that the changes ported from MAME to the M68K core are correct but I will assume so. I don't see anything that really stands out there. The Z80 changes concern me most and I am not sure they are needed at all.

2022-08-07 21:46 UTC, toxieainc commented on Src/CPU/Z80/Z80.cpp
> +      OUTPUT(lreg(BC), lreg(0));
I just ported this from https://www.mathematik.uni-ulm.de/users/ag/yaze-ag/ which is the source you also cite somewhere

2022-08-07 21:46 UTC, toxieainc commented on Src/CPU/Z80/Z80.cpp
> +      if (BC == 0)
I just ported this from https://www.mathematik.uni-ulm.de/users/ag/yaze-ag/ which is the source you also cite somewhere

2022-08-07 21:47 UTC, toxieainc commented on Src/CPU/Z80/Z80.cpp
> +        BC = 0x10000;
I just ported this from https://www.mathematik.uni-ulm.de/users/ag/yaze-ag/ which is the source you also cite somewhere

2022-08-07 21:47 UTC, toxieainc commented on Src/CPU/Z80/Z80.cpp
> +        BC = 0x10000;
I just ported this from https://www.mathematik.uni-ulm.de/users/ag/yaze-ag/ which is the source you also cite somewhere

2022-08-07 21:47 UTC, toxieainc commented on Src/CPU/Z80/Z80.cpp
> +        BC = 0x10000;
I just ported this from https://www.mathematik.uni-ulm.de/users/ag/yaze-ag/ which is the source you also cite somewhere

2022-08-07 21:47 UTC, toxieainc commented on Src/CPU/PowerPC/ppc_ops.c
>  {
This comes from MAME.

2022-08-07 21:47 UTC, toxieainc commented on Src/CPU/PowerPC/ppc_ops.c
>  {
This comes from MAME.

2022-08-07 22:28 UTC, trzy commented on Src/CPU/Z80/Z80.cpp
> +      if (BC == 0)
I think I see what's going on but it makes no sense to do this either here or in the YAZE-AG source code, where the BC register is also a 16-bit variable. So what happens when we assign 0x10000? I believe the rule is that it will be truncated to 0 anyway.

I took a look at the LDIR instruction. It is basically just using BC as a counter to perform a repeated load with auto-increment of src and dest (basically, a memcpy). See here: http://z80-heaven.wikidot.com/instructions-set:ldir

Now, when BC is 0, this instruction will loop around until BC==0 again. I think the loop condition already satisfies this because it is a do-while loop that checks for --BC == 0 (pre-decrement). So, if BC == 0, it will loop 65536 times.

Unless I'm really missing something important, it would appear that the code is already correct and this added statement is completely redundant both here and in YAZE-AG. Therefore, I would say it is best to leave the Z80 core as-is for now and back out all the changes. I don't think any of them have a functional impact?

2022-08-08 07:16 UTC, toxieainc commented on Src/CPU/Z80/Z80.cpp
> +      if (BC == 0)
Yup, no problem. Will do.

2022-08-08 07:20 UTC, toxieainc commented
This should now be good to go given your review. Thanks!!

2022-08-10 03:37 UTC, trzy commented
Thanks for removing the Z80 stuff. I think this looks good!

2022-08-10 03:37 UTC, merged