Fix version warnings
trzy/Supermodel pull request #8
Opened 2022-07-22 22:19 UTC by toxieainc

At least the Intel GLSL compiler complains on each startup of Supermodel about the GLSL version missing in those shaders.

2022-08-10 03:41 UTC, trzy requested changes
Need to remove the CPU/ stuff from this as well as it has already been merged in.

2022-08-10 05:56 UTC, toxieainc commented on Src/Graphics/New3D/R3DFrameBuffers.cpp
> +			vec3 col1 = colTrans1.rgb * colTrans1.a;
Just to save 3 or 4 instructions (unless the compiler is smart enough). The division is done some lines below (combined).

2022-08-10 05:59 UTC, toxieainc commented
Also rebased all, so the Z80 changes are also gone here (sorry for that, should've created 3 separate branches in the 1st place :/).

2022-08-12 02:42 UTC, trzy commented
Thanks, I want to give this a spin this weekend on some other systems and if all goes well will give final approval.

2022-08-19 06:15 UTC, toxieainc commented
Could this be pushed? Its absolutely harmless and is pretty much equivalent to what is already there (minus triggering the missing version warnings ;))

2022-08-19 15:41 UTC, trzy commented
Sure!

2022-08-19 15:41 UTC, merged